#!/bin/bash

echo "----------"
echo "GIT POST RECEIVE HOOK"
echo "User: $USER"
echo "Host: $HOSTNAME"
echo "Path: $PWD"

while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname) || { echo 'Could not set $branch'; echo 'Exiting ...' ; exit 1; }
    echo "Branch: $branch"

    if ! [ "$branch" == "feature/deploy-pipeline" ] ; then
      echo "This is not a deployable branch."
      echo "Exiting ..."
      exit 1;
    fi

    revision=$(git rev-parse $branch) || { echo 'Could not set $revision' ; exit 1; }
    echo "Revision: $revision"

    echo "mkdir ../releases/$revision/"
    mkdir ../releases/$revision/ || { echo "Could not create ../releases/$revision/"; echo 'Exiting ...' ; exit 1; }

    echo "git --work-tree=../releases/$revision/ --git-dir=./ checkout $branch -f"
    git --work-tree=../releases/$revision/ --git-dir=./ checkout $branch -f

    echo "cd ../releases/$revision/"
    cd ../releases/$revision/

    echo "yarn install"
    yarn install

    echo "ember build -prod"
    ember build -prod

    echo "node fastboot-server.js"
    node fastboot-server.js
done
echo "----------"
