#!/bin/bash

set -e
set -o pipefail

echo "----------"
echo "GIT POST RECEIVE HOOK"
echo "User: $USER"
echo "Host: $HOSTNAME"
echo "Path: $PWD"

while read oldrev newrev refname
do

    echo "oldrev: $USER"
    echo "newrev: $HOSTNAME"
    echo "refname: $refname"

    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    echo "Branch: $branch"

    if ! [ "$branch" == "feature/deploy-pipeline" ] ; then
      echo "This is not a deployable branch."
      echo "Exiting ..."
      exit 1;
    fi

    revision=$(git rev-parse $branch)
    echo "Revision: $revision"

    echo "cd ../"
    cd ../

    echo "pwd"
    pwd

    gitdir="repo/"
    worktree="releases/$revision/"
    current="current/"

    echo "gitdir: $gitdir"
    echo "worktree: $worktree"
    echo "current: $current"

    echo "mkdir $worktree"
    mkdir $worktree

    echo "git --work-tree=$worktree --git-dir=$gitdir checkout $branch -f"
    git --work-tree=$worktree --git-dir=$gitdir checkout $branch -f

    echo "cd $worktree"
    cd $worktree

    # echo "nvm install"
    # nvm install

    echo "yarn install"
    yarn install

    echo "ember build -prod"
    ember build -prod

    echo "ln -sf $worktree $current"
    ln -sf $worktree $current

done
echo "----------"
