#!/bin/bash
echo "----------"
echo "User: $USER"
echo "Server: $HOSTNAME"
echo "Path: $PWD"
while read oldrev newrev refname
do
    echo "Repo: $(node -p -e "require('./package.json').repository")"
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    echo "Branch: $branch"
    if [ "$branch" == "feature/deploy-pipeline" ] ; then
      echo "git checkout feature/deploy-pipeline -f"
      git checkout feature/deploy-pipeline -f
      echo "yarn install"
      yarn install
      echo "ember build -prod"
      ember build -prod
      echo "node fastboot-server.js"
      node fastboot-server.js
    else
      echo "Doing nothing... Unless you push the master branch."
    fi
done
echo "End"
echo "----------"
