#!/bin/bash

set -e
set -o pipefail

echo "----------"
echo "GIT POST RECEIVE HOOK"
echo "User: $USER"
echo "Host: $HOSTNAME"
echo "Path: $PWD"

while read oldrev newrev refname
do
    echo "oldrev: $oldrev"
    echo "newrev: $newrev"
    echo "refname: $refname"

    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    echo "Branch: $branch"

    if ! [ "$branch" == "feature/deploy-pipeline" ] ; then
      echo "This is not a deployable branch."
      echo "Ending deployment."
      exit 1;
    fi

    cd ../
    echo "Path: $PWD"

    echo "git checkout $branch -f"
    git checkout $branch -f

    echo "yarn install"
    yarn install

    echo "ember build -prod"
    ember build -prod
done
echo "----------"
