timeout_in_minutes: 10
steps:
  - name: ':ember:'
    command:
      - 'yarn install'
      - 'ember test'

  - wait

  - name: ':rocket:'
    branches: 'production'
    command:
      - 'git fetch'
      - 'git checkout production'
      - 'git pull'
      - 'git push server production'
