timeout_in_minutes: 10
steps:
  - name: ':ember:'
    command:
      - 'yarn install'
      - 'ember test'

  - wait

  - name: ':rocket:'
    branches: 'production'
    command:
      - 'echo "git fetch"'
      - 'git fetch'
      - 'echo "git checkout production -f"'
      - 'git checkout production -f'
      - './deploy.sh'
