timeout_in_minutes: 10
steps:
  - name: ':hamster:'
    command:
      - 'yarn install'
      - 'ember test'

  - wait

  - name: ':rocket:'
    branches: 'feature/deploy-pipeline'
    command:
      - 'git push server feature/deploy-pipeline'
